routes:

collections:
  /:
    permalink: '/{year}/{month}/{slug}/'
    template:
      - index
    filter: 'tag:news'
  /guide/:
    permalink: '/guide/{slug}/'
    template:
      - index
    filter: 'tag:guide'

taxonomies:
  tag: /topic/{slug}/
  author: /author/{slug}/
